### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by hardikJoshi123** [thelinmichael/face-recognition#1]
From where i get libraries which you use in this project. I download OpenCV and facebook sdk but not able to add libraries to this project.

**Comment by thelinmichael** [comment]
Hey hardikJoshi123, thanks for showing interest in this little project. I'm a bit busy at the moment, but I'm planning to update the code so that it works with the latest Facebook and OpenCV APIs. I'll also write an install guide. I'll let you know here when I'm done.

**Comment by hardikJoshi123** [comment]
Ok thanks @thelinmichael

**Comment by thelinmichael** [comment]
@hardikJoshi123, I've chosen to not continue working on this project as the versions of the dependencies (OpenCV) and SDKs (Android, Facebook) are pretty much deprecated and would need heavy rewriting to function with up-to-date versions. I'll keep the repo around if anyone is interested in how things could've been done back in '11, but there should be lots of similar open source applications out there.

**Comment by hardikJoshi123** [comment]
ok thanks for reply.. And thanks for you sample.
